//MAIN TYPES
export const SHOW_LOADER = 'SHOW_LOADER';
export const FETCH_DATA = 'FETCH_DATA';
export const ADD_ITEM = 'ADD_ITEM';
export const SHOW_ADD_FORM = 'SHOW_ADD_FORM';
export const SHOW_ITEM_CARD = 'SHOW_ITEM_CARD';
//FILTER TYPES
export const FILTER_ID = 'FILTER_ID';
export const FILTER_FIRSTNAME = 'FILTER_FIRSTNAME';
export const FILTER_LASTNAME = 'FILTER_LASTNAME';
export const FILTER_EMAIL = 'FILTER_EMAIL';
export const FILTER_PHONE = 'FILTER_PHONE';